### PR TITLE
remove deprecated io/ioutils, minor refactor to reduce DRY, update go1.18

### PR DESCRIPTION
**Pull request by thaJeztah**
see individual commits for details

### CODE REVIEW

**Comment by thaJeztah** [comment]
@kunalkushwaha @AkihiroSuda @estesp PTAL

**Comment by thaJeztah** [comment]
follow-up is in https://github.com/kunalkushwaha/ltag/pull/14

**Review by estesp — APPROVED** [review]
LGTM

**Review by kunalkushwaha — APPROVED** [review]
Thanks for PR.
LGTM

**Comment by thaJeztah** [comment]
Thanks for reviewing! Let me rebase https://github.com/containerd/containerd/pull/7316 and move it out of draft

**Comment by thaJeztah** [comment]
Oops; I meant https://github.com/kunalkushwaha/ltag/pull/14 of course 🤦 (wrong link)

**Pull request merged**
