### PR TITLE
 golang: support Go 1.17 compiler flags (e.g., `//go:build !windows`)

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Required for https://github.com/containerd/containerd/pull/5903

@kunalkushwaha Could you create a new release with this?

### CODE REVIEW

**Comment by kunalkushwaha** [comment]
Thanks for PR. LGTM

**Comment by kunalkushwaha** [comment]
Merging.

**Comment by kunalkushwaha** [comment]
Please find the new release tag  https://github.com/kunalkushwaha/ltag/releases/tag/v0.2.3

**Comment by AkihiroSuda** [comment]
Thanks!

**Pull request merged**
